config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server, at: '/cable'
  default_url_options :host => "103.166.185.90"
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/login'
  get "/books", to: "books#index"
  get 'books/show'
  get 'books/create'
  get 'books/destroy'
  post 'books/read', to: "books#read"
  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/register", to: "users#new"
  post "/register", to: "users#create"
  delete '/logout', to: 'sessions#destroy'
  get "/search", to: "books#search"
  get "/links", to: "links#index"
  get "/search_local_book", to: "local_books#search"
  post "search_local_book", to: "local_book#index"
  resources :users
  resources :books
  resources :local_books
  resources :password_resets, only: [:new, :create, :edit, :update]

  namespace :admin do
    root "statistics#index"
    get "/admin", to: "statistics#index"
    get "/books", to: "books#index"
    post "/books/:id", to: "books#update"
    get "/add_book", to: "books#new"
    post "/add_book", to: "books#create"
    get "/add_class", to: "class_users#new"
    post "/add_class", to: "class_users#create"
    get "/add_user", to: "users#new"
    post "/add_user", to: "users#create"
    get "/add_subject", to: "subjects#new"
    post "/add_subject", to: "subjects#create"
    get "/add_category", to: "categories#new"
    post "/add_category", to: "categories#create"
    get "/add_link", to: "links#new"
    post "/add_link", to: "links#create"
    get "/add_local_book", to: "local_books#new"
    post "/add_local_book", to: "local_books#create"
    resources :static_pages
    resources :books
    resources :local_books
    resources :users
    resources :class_users
    resources :subjects
    resources :categories
    resources :links
    resources :statistics
  end
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :doc_file, dependent: :destroy
  has_many_attached :doc_file_pages, dependent: :destroy
  belongs_to :subject
  belongs_to :category
  belongs_to :user

  scope :asc_title, ->{order title: :asc}
  scope :book_time, ->(start_d,end_d) {where("created_at >= ? and created_at <= ?", start_d, end_d)}

  delegate :name, to: :subject, prefix: :subject, allow_nil: true
  delegate :name, to: :category, prefix: :category, allow_nil: true
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < Admin::BaseController
    before_action :find_book, except: %i(index new create)
    def index
      @categories = Category.asc_name
      @teachers = User.asc_name.where("role = 1")
      @q = Book.asc_title.ransack(params[:q])
      @pagy, @books = pagy(@q.result, items: 8)
    end

    def show; end

    def new
      @subjects = Subject.asc_name
      @categories = Category.asc_name
      @book = Book.new
    end


    def create
      @book = Book.new(book_params)
      @book.user_id = current_user.id
      respond_to do |format|
        if @book.save
          CreateImagesOfPdfPagesJob.set(wait: 2.seconds).perform_later(@book.id)
          format.js
          format.html { redirect_to root_path, notice: "book was successfully created." }
          format.json { render :show, status: :created, location: @book }
        else
          format.js
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @book.errors, status: :unprocessable_entity }
        end
      end
    end


    def edit
      @subjects = Subject.asc_name
      @categories = Category.asc_name
      @teachers = User.where("role = 1")
    end

    def update
      if @book.update book_params
        flash[:success] = "Book updated"
        redirect_to admin_books_path
      else
        flash[:danger] = "Not updated book"
        render :edit
      end
    end

    def destroy
      @book.destroy
      respond_to do |format|
        format.html { redirect_to admin_books_url, notice: "book was successfully destroyed." }
        format.json { head :no_content }
      end
    end

      private

      def set_book
        @book = book.find(params[:id])
      end

    def book_params
      params.require(:book).permit(:id, :title, :author,
                                    :subject_id, :grade, :category_id, :user_id, :describe, :publish_on, :doc_file)
    end

    def find_book
      @book = Book.find_by id: params[:id]
      return if @book

      flash[:danger] = "Sách không tồn tại"
      redirect_to admin_books_url
    end
  end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :logged_in_user, only: [:show]
    BOOKS_PER_PAGE = 6

    def index
        if (params[:sorts]) then
            @sorts = params[:sorts]



        else
            @sorts = "title"
        end
        @subject_list = Subject.asc_name
        @category_list = Category.asc_name
        @subject = params[:subject] ? params[:subject] : []
        @category = params[:category] ? params[:category] : []
        @page = [params.fetch(:page, 1).to_i, 1].max
        @totalPage = (Book.all.count * 1.0 / BOOKS_PER_PAGE).ceil
        @books = Book.all
        if (@subject.length > 0)
            @books = @books.where("subject_id in (?)", @subject)
        end
        if (@category.length > 0)
            @books = @books.where("category_id in (?)", @category)
        end
        @total_books_user = @books
        @pagy, @books = pagy(@books.order(@sorts), items: BOOKS_PER_PAGE)
    end

    def new
    end

    def search
        @query = params[:q] ? params[:q] : ""
        @totalResult = Book.where("title LIKE ?", "%" + @query + "%").count
        @totalPage = (@totalResult* 1.0 / BOOKS_PER_PAGE).ceil
        @page = [params.fetch(:page, 1).to_i, 1].max
        @books = Book.where("title LIKE ?", "%" + @query + "%").order("title").offset((@page - 1) * BOOKS_PER_PAGE).limit(BOOKS_PER_PAGE)
    end


    def show
        @book = Book.find(params[:id])
    end

    def read
        @book = Book.find(params[:id])
        num_watch = @book.num_watch + 1
        @book.update_attribute :num_watch, num_watch
    end
  end

app/views/admin/books/_waiting_modal.html.erb
<div class="modal-dialog modal-dialog-centered" role="book">
  <div class="modal-content">
    <div class="modal-body">
      <p class="lead text-center">We are preparing your book. This will take some time.</p>
      <div id="conversion-progress-bar" class="progress" data-last-uploaded-book-id="<%= book_id %>"></div>
      <p id="converted-page-number" class="ml-2" data-last-uploaded-book-id="<%= book_id %>"><span class="text-primary font-weight-bold">Status:</span> Preparing book</p>
      <div id="alert-message">
        <p>If you need to come back later, your book can be found in the drafts section <a href="/books/<%= book_id %>" target="_blank" class="text-primary font-weight-bold">here</a>.</p>
      </div>
    </div>
  </div>
</div>

app/views/admin/books/create.js.erb
$("#exampleModal").html("<%= escape_javascript render('admin/books/waiting_modal', book_id: @book.id) %>");
$("#exampleModal").modal('show');

app/views/admin/books/edit.html.erb
<div class="admin-page">
  <div> <%= render "admin/static_pages/sidebar" %> </div>
  <div class="form-container">
    <div class="form row">
      <div class="add-book">
        <p class="form-title">Thêm sách</p>
        <%= form_for([:admin, @book], remote: true) do |f| %>
          <%= render "admin/shared/error_messages", object: f.object %>
          <%= f.label :title, "Tiêu đề" %>
          <%= f.text_field :title, class: "form-control" %>
          <%= f.label :author, "Tác giả" %>
          <%= f.text_field :author, class: "form-control" %>
          <%= f.label :describe, "Miêu tả" %>
          <%= f.text_area :describe, class: "form-control" %>
          <%= f.label :grade, "Khối" %>
          <%= f.select :grade, options_for_select([["1", "1"], ["2", "2"], ["3", "3"], ["4", "4"], ["5", "5"], ["Mọi lứa tuổi", "Mọi lứa tuổi"]]), class: "form-control"%>
          <%= f.label :subject, "Môn học" %>
          <%= collection_select(:book, :subject_id, @subjects, :id, :name) %>
          <%= f.label :category, "Loại sách" %>
          <%= collection_select(:book, :category_id, @categories, :id, :name) %>
          <%= f.label :user_id, "Người đăng" %>
          <%= collection_select(:book, :user_id, @teachers, :id, :name, include_blank: true) %>
          <%= f.label :publish_on, "Ngày xuất bản" %>
          <%= f.date_field :publish_on, class: "form-control"%>
          <%= f.submit "Update", class: "submit-btn" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/books/index.html.erb
<div class="admin-page">
  <div> <%= render "admin/static_pages/sidebar" %> </div>
  <div class="book-manage-page">
    <div class="container">
      <%= search_form_for [:admin, @q] do |f| %>
        <div class="form-section">
          <div class="col-6">
            <%= f.label :title_cont %>
            <%= f.search_field :title_cont %>
          </div>
          <div class="col-1">
            <%= f.label :grade_cont %>
            <%= f.select :grade_cont, options_for_select([["",""],["1", "1"], ["2", "2"], ["3", "3"], ["4", "4"], ["5", "5"], ["Mọi lứa tuổi","Mọi lứa tuổi"]]), class: "form-control"%>
          </div>
          <div class="col-1">
            <%= f.label :category_id_eq %>
            <%= f.select :category_id_eq, Category.asc_name.collect {|category| [category.name, category.id]}, include_blank: true , class: "form-control"%>
          </div>
          <div class="col-1">
            <%= f.label :subject_id_eq %>
            <%= f.select :subject_id_eq, Subject.asc_name.collect {|subject| [subject.name, subject.id]}, include_blank: true , class: "form-control"%>
          </div>
          <div class="col-1">
            <%= f.label :by_teacher %>
            <%= f.select :user_id_eq, @teachers.collect {|teacher| [teacher.name, teacher.id]}, include_blank: true , class: "form-control"%>
          </div>
          <div class="col-1">
            <%= sort_link(@q, :num_watch,"Hot", default_order: :desc) %>
          </div>
        </div>
        <%= f.submit %>
      <% end %>
    </div>
    <div class="book-list">
      <% @books.each do |book| %>
        <%= link_to admin_book_path(book) do %>
          <div class="book-item-row">
            <div class="image-wrapper">
              <% if book.doc_file_pages.first %>
                <%= image_tag book.doc_file_pages.first %>
              <% end %>
            </div>
            <div class="detail-wrapper">
              <p class="title">
                <%= book.title %>
                <span class="author">by <%= book.author %></span>
              </p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <%== pagy_nav(@pagy) %>
  </div>
</div>

app/views/admin/books/new.html.erb
<div class="admin-page">
  <div> <%= render "admin/static_pages/sidebar" %> </div>
  <div class="form-container">
    <div class="form row">
      <div class="add-book">
        <p class="form-title">Thêm sách</p>
        <%= form_for([:admin, @book], remote: true) do |f| %>
          <%= render "admin/shared/error_messages", object: f.object %>
          <%= f.label :title, "Tiêu đề" %>
          <%= f.text_field :title, class: "form-control" %>
          <%= f.label :author, "Tác giả" %>
          <%= f.text_field :author, class: "form-control" %>
          <%= f.label :describe, "Miêu tả" %>
          <%= f.text_area :describe, class: "form-control" %>
          <%= f.label :grade, "Khối" %>
          <%= f.select :grade, options_for_select([["1", "1"], ["2", "2"], ["3", "3"], ["4", "4"], ["5", "5"], ["Mọi lứa tuổi", "Mọi lứa tuổi"]]), class: "form-control"%>
          <%= f.label :subject, "Môn học" %>
          <%= collection_select(:book, :subject_id, @subjects, :id, :name) %>
          <%= f.label :category, "Loại sách" %>
          <%= collection_select(:book, :category_id, @categories, :id, :name) %>
          <%= f.label :publish_on, "Ngày xuất bản" %>
          <%= f.date_field :publish_on, class: "form-control"%>
          <%= f.label :upload_file %>
          <%= f.file_field :doc_file, required: true %>
          <%= f.submit "Add", class: "submit-btn" %>
        <% end %>
      </div>
    </div>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    </div>
  </div>

app/views/admin/books/show.html.erb
<div class="admin-page">
  <div> <%= render "admin/static_pages/sidebar" %> </div>
  <div class="book-detail-page">
    <div class="image-wrapper">
    <% if @book.doc_file_pages.last %>
      <%= image_tag @book.doc_file_pages.first, width: "100%" %>
      <% end %>
    </div>
    <div class="detail-section">
      <div class="book-detail">
        <div class="header">
          <span class="book-title"><%= @book.title %> </span> by <span class="book-author"><%= @book.author %> </span>
        </div>
        <div class="detail">
          <div class="book-subject">
            Môn học: <%= @book.subject.name %>
          </div>
          <div class="book-subject">
            Lớp: <%= @book.grade %>
          </div>
          <div class="book-describe">
            Danh mục: <%= @book.category.name %>
          </div>
          <div class="book-describe">
            Miêu tả: <%= @book.describe %>
          </div>
        </div>
      </div>
      <% if current_user.admin? %>
      <div class="functional-btn">
        <%= link_to edit_admin_book_path(@book) do %>
          <span class="fa fa-edit"></span>
        <% end %>
      </div>
      <div class="functional-btn">
        <%= link_to admin_book_path(@book), method: :delete, data: { confirm: "Bạn có chắc là muốn xóa không?" } do %>
          <span class="fa fa-trash"></span>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>