config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server, at: '/cable'
  default_url_options :host => "103.166.185.90"
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/login'
  get "/books", to: "books#index"
  get 'books/show'
  get 'books/create'
  get 'books/destroy'
  post 'books/read', to: "books#read"
  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/register", to: "users#new"
  post "/register", to: "users#create"
  delete '/logout', to: 'sessions#destroy'
  get "/search", to: "books#search"
  get "/links", to: "links#index"
  get "/search_local_book", to: "local_books#search"
  post "search_local_book", to: "local_book#index"
  resources :users
  resources :books
  resources :local_books
  resources :password_resets, only: [:new, :create, :edit, :update]

  namespace :admin do
    root "statistics#index"
    get "/admin", to: "statistics#index"
    get "/books", to: "books#index"
    post "/books/:id", to: "books#update"
    get "/add_book", to: "books#new"
    post "/add_book", to: "books#create"
    get "/add_class", to: "class_users#new"
    post "/add_class", to: "class_users#create"
    get "/add_user", to: "users#new"
    post "/add_user", to: "users#create"
    get "/add_subject", to: "subjects#new"
    post "/add_subject", to: "subjects#create"
    get "/add_category", to: "categories#new"
    post "/add_category", to: "categories#create"
    get "/add_link", to: "links#new"
    post "/add_link", to: "links#create"
    get "/add_local_book", to: "local_books#new"
    post "/add_local_book", to: "local_books#create"
    resources :static_pages
    resources :books
    resources :local_books
    resources :users
    resources :class_users
    resources :subjects
    resources :categories
    resources :links
    resources :statistics
  end
end

app/models/class_user.rb
class ClassUser < ApplicationRecord
  has_many :users, dependent: :nullify
  scope :asc_name, ->{order name: :asc}
end

app/controllers/admin/class_users_controller.rb
class Admin::ClassUsersController < Admin::BaseController
    def index
      @query = params[:q] ? params[:q] : "";
      @result = ClassUser.where("name LIKE ? OR grade LIKE ?", "%" + @query + "%", "%" + @query + "%")
      @result = @result.asc_name
      @pagy, @class_users = pagy(@result, items: 8)
    end

    def new
      @class_user = ClassUser.new
    end

    def create
      @class_user = ClassUser.new class_user_params
    if @class_user.save
      flash[:success] = "welcome"
      redirect_to admin_class_users_path
    else
      flash[:danger] = "danger"
      render :new
    end
    end

    def edit
      @class_user = ClassUser.find(params[:id])
    end

    def update
      @class_user = ClassUser.find(params[:id])
      if @class_user.update class_user_params
        flash[:success] = "Profile updated"
        redirect_to admin_class_users_path
      else
        flash[:danger] = "danger"
        render :edit
      end
    end

    def destroy
      @class_user = ClassUser.find_by id: params[:id]
      if @class_user.destroy
        flash[:success] = "success"
      else
        flash[:danger] = "danger"
      end
      redirect_to admin_class_users_path
    end

    private

    def class_user_params
      params.require(:class_user).permit(:id, :name, :grade)
    end

  end

app/views/admin/class_users/edit.html.erb
<div class="admin-page">
  <div> <%= render "admin/static_pages/sidebar" %> </div>
  <div class="form-container">
    <div class="form row">
      <div class="edit-account">
        <p class="form-title">Chỉnh sửa lớp</p>
        <%= form_for [:admin, @class_user] do |f| %>
          <%= render "admin/shared/error_messages", object: f.object %>
          <%= f.label :name, "Tên" %>
          <%= f.text_field :name, class: "form-control" %>
          <%= f.label :grade, "Khối" %>
          <%= f.select :grade, options_for_select([["1", "1"], ["2", "2"], ["3", "3"], ["4", "4"], ["5", "5"]]), class: "form-control" %>
          <%= f.submit "Edit", class: "submit-btn" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/class_users/index.html.erb
<div class="admin-page">
  <div> <%= render "admin/static_pages/sidebar" %> </div>
  <div class="account-manage-page">
    <form class="search-form-wrapper" >
      <input name="q" type="text" placeholder="Nhập nội dung tìm kiếm" value="<%= params[:q] %>"/>
      <input type="submit" hidden />
      <button type="submit" class="search-btn"><span class="fa fa-search"></span></button>
    </form>
    <table class="rwd-table">
      <thead>
        <tr>
          <th>Tên</th>
          <th>Khối</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @class_users.each do |class_user| %>
          <tr>
            <td><%= class_user.name %></td>
            <td><%= class_user.grade %></td>
            <td>
              <div class="action-btn">
                <%= link_to edit_admin_class_user_path(class_user) do %>
                  <span class="fa fa-edit"></span>
                <% end %>
                <%= link_to admin_class_user_path(class_user), method: :delete, data: { confirm: "Bạn có chắc là muốn xóa không?" } do %>
                  <span class="fa fa-trash"></span>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%== pagy_nav(@pagy) %>
  </div>
</div>

app/views/admin/class_users/new.html.erb
<div class="admin-page">
  <div> <%= render "admin/static_pages/sidebar" %> </div>
  <div class="form-container">
    <div class="form row">
      <div class="edit-account">
        <p class="form-title">Thêm lớp</p>
        <%= form_for [:admin, @class_user] do |f| %>
          <%= render "admin/shared/error_messages", object: f.object %>
          <%= f.label :name, "Tên" %>
          <%= f.text_field :name, class: "form-control" %>
          <%= f.label :grade, "Khối" %>
          <%= f.select :grade, options_for_select([["1", "1"], ["2", "2"], ["3", "3"], ["4", "4"], ["5", "5"]]), class: "form-control" %>
          <%= f.submit "Add", class: "submit-btn" %>
        <% end %>
      </div>
    </div>
  </div>
</div>