config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server, at: '/cable'
  default_url_options :host => "103.166.185.90"
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/login'
  get "/books", to: "books#index"
  get 'books/show'
  get 'books/create'
  get 'books/destroy'
  post 'books/read', to: "books#read"
  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/register", to: "users#new"
  post "/register", to: "users#create"
  delete '/logout', to: 'sessions#destroy'
  get "/search", to: "books#search"
  get "/links", to: "links#index"
  get "/search_local_book", to: "local_books#search"
  post "search_local_book", to: "local_book#index"
  resources :users
  resources :books
  resources :local_books
  resources :password_resets, only: [:new, :create, :edit, :update]

  namespace :admin do
    root "statistics#index"
    get "/admin", to: "statistics#index"
    get "/books", to: "books#index"
    post "/books/:id", to: "books#update"
    get "/add_book", to: "books#new"
    post "/add_book", to: "books#create"
    get "/add_class", to: "class_users#new"
    post "/add_class", to: "class_users#create"
    get "/add_user", to: "users#new"
    post "/add_user", to: "users#create"
    get "/add_subject", to: "subjects#new"
    post "/add_subject", to: "subjects#create"
    get "/add_category", to: "categories#new"
    post "/add_category", to: "categories#create"
    get "/add_link", to: "links#new"
    post "/add_link", to: "links#create"
    get "/add_local_book", to: "local_books#new"
    post "/add_local_book", to: "local_books#create"
    resources :static_pages
    resources :books
    resources :local_books
    resources :users
    resources :class_users
    resources :subjects
    resources :categories
    resources :links
    resources :statistics
  end
end

app/controllers/admin/static_pages_controller.rb
class Admin::StaticPagesController < Admin::BaseController
  def index
  end

  def account_list
  end

  def add_acount
  end

  def book_list
  end

  def add_book
    @book = Book.new
  end

  def create_book
    @book = Book.new(book_params)
    if @book.save
      redirect_to admin_root_path
    else
      flash[:alert] = "Something was wrong"
      render :new
    end
  end

  def book_params
    params.required(:book).permit(:title, :content, :author, :subject, :describe, :image, :publish_on)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home;
    @categories = Category.all.limit(4)
    @subjects = Subject.asc_name
    @books = Book.order(updated_at: :desc).limit(8)
  end

  def about; end

  def login; end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/static_pages/_sidebar.html.erb
<div class="sidebar">
   <base href="admin">
   <h3 class="title">Menu</h3>
   <div class="sidebar-button menu" onclick="onMenuClick('account')">
      <span class="fa fa-user"></span> Quản lý tài khoản
   </div>
   <%= link_to "Danh sách tài khoản", admin_users_path, class: "sidebar-button sub-menu account"%>
   <%= link_to "Thêm tài khoản", admin_add_user_path, class: "sidebar-button sub-menu account"%>

   <%= link_to admin_statistics_path, class: "sidebar-button" do %>
      <span class="fa fa-bar-chart"></span> Thống kê
   <% end %>

   <div class="sidebar-button menu" onclick="onMenuClick('class')">
      <span class="fa fa-building"></span> Quản lý lớp
   </div>
   <%= link_to "Danh sách lớp", admin_class_users_path, class: "sidebar-button sub-menu class"%>
   <%= link_to "Thêm lớp", admin_add_class_path, class: "sidebar-button sub-menu class"%>

   <div class="sidebar-button menu" onclick="onMenuClick('book')">
      <span class="fa fa-book"></span> Quản lý sách
   </div>
   <%= link_to "Danh sách sách", admin_books_path, class: "sidebar-button sub-menu book"%>
   <%= link_to "Thêm sách", new_admin_book_path, class: "sidebar-button sub-menu book"%>

   <div class="sidebar-button menu" onclick="onMenuClick('subject')">
      <span class="fa fa-briefcase"></span> Quản lý môn học
   </div>
   <%= link_to "Danh sách môn học", admin_subjects_path, class: "sidebar-button sub-menu subject"%>
   <%= link_to "Thêm môn học", new_admin_subject_path, class: "sidebar-button sub-menu subject"%>

   <div class="sidebar-button menu" onclick="onMenuClick('category')">
      <span class="fa fa-sitemap"></span> Quản lý loại sách
   </div>
   <%= link_to "Danh sách loại sách", admin_categories_path, class: "sidebar-button sub-menu category"%>
   <%= link_to "Thêm loại sách", new_admin_category_path, class: "sidebar-button sub-menu category"%>

   <div class="sidebar-button menu" onclick="onMenuClick('local_book')">
     <span class="fa fa-globe"></span> Quản lý sách hiện có trên trường
   </div>
   <%= link_to "Danh sách loại sách", admin_local_books_path, class: "sidebar-button sub-menu local_book"%>
   <%= link_to "Thêm loại sách", new_admin_local_book_path, class: "sidebar-button sub-menu local_book"%>

   <div class="sidebar-button menu" onclick="onMenuClick('link')">
      <span class="fa fa-link"></span> Quản lý đường dẫn thư viện mở rộng
   </div>
   <%= link_to "Danh sách đường dẫn", admin_links_path, class: "sidebar-button sub-menu link"%>
   <%= link_to "Thêm đường dẫn", new_admin_link_path, class: "sidebar-button sub-menu link"%>

   <%= link_to "Đăng xuất", logout_path, method: :delete, class: "sidebar-button"%>
</div>
<%= javascript_pack_tag "menu" %>