config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server, at: '/cable'
  default_url_options :host => "103.166.185.90"
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/login'
  get "/books", to: "books#index"
  get 'books/show'
  get 'books/create'
  get 'books/destroy'
  post 'books/read', to: "books#read"
  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/register", to: "users#new"
  post "/register", to: "users#create"
  delete '/logout', to: 'sessions#destroy'
  get "/search", to: "books#search"
  get "/links", to: "links#index"
  get "/search_local_book", to: "local_books#search"
  post "search_local_book", to: "local_book#index"
  resources :users
  resources :books
  resources :local_books
  resources :password_resets, only: [:new, :create, :edit, :update]

  namespace :admin do
    root "statistics#index"
    get "/admin", to: "statistics#index"
    get "/books", to: "books#index"
    post "/books/:id", to: "books#update"
    get "/add_book", to: "books#new"
    post "/add_book", to: "books#create"
    get "/add_class", to: "class_users#new"
    post "/add_class", to: "class_users#create"
    get "/add_user", to: "users#new"
    post "/add_user", to: "users#create"
    get "/add_subject", to: "subjects#new"
    post "/add_subject", to: "subjects#create"
    get "/add_category", to: "categories#new"
    post "/add_category", to: "categories#create"
    get "/add_link", to: "links#new"
    post "/add_link", to: "links#create"
    get "/add_local_book", to: "local_books#new"
    post "/add_local_book", to: "local_books#create"
    resources :static_pages
    resources :books
    resources :local_books
    resources :users
    resources :class_users
    resources :subjects
    resources :categories
    resources :links
    resources :statistics
  end
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  enum role: {admin: 0, teacher: 1, student: 2}
  ransacker :role, formatter: proc {|v| roles[v]} do |parent|
    parent.table[:role]
  end
  has_one :user_access, dependent: :destroy
  has_many :books
  belongs_to :class_user

  attr_accessor :reset_token

  before_save :downcase_Tk, :check_email_unique

  validates :name, presence: true, length: { maximum: 40 }
  validates :Tk, presence: true, length: {minium: 10, maximum: 100}, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, if: :password
  validates :email, length: {in: 10..255}, uniqueness: {case_sensitive: false}, allow_blank: true

  scope :asc_name, ->{order name: :asc}
  scope :student_with, ->id {where("class_user_id = ?", id)}


  delegate :name, to: :class_user, prefix: :class_user, allow_nil: true

  has_secure_password

  class << self
    def digest string
      cost = if ActiveModel::SecurePassword.min_cost
               BCrypt::Engine::MIN_COST
             else
               BCrypt::Engine.cost
             end
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update reset_digest: User.digest(reset_token)
    update reset_sent_at: Time.zone.now
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  def password_reset_expired?
    reset_sent_at < 24.hours.ago
  end

  def check_email_unique
    return if email.blank?
    user = User.find_by email: email
    return false if user.present?
  end

  def downcase_Tk
    self.Tk.downcase!
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
    def index
      if current_user.teacher?
        @q = User.student_with(current_user.class_user_id).asc_name.ransack(params[:q])
        @pagy, @users = pagy(@q.result, items: 10)
      else
        @q = User.asc_name.ransack(params[:q])
        @pagy, @users = pagy(@q.result, items: 10)
      end

    end

    def edit
      @class_users = ClassUser.asc_name
      @user = User.find_by id: params[:id]
    end

    def new
        @class_users = ClassUser.asc_name
        @user = User.new
    end

    def update
      params[:id] = params[:id].to_i
      @user = User.find_by id: params[:id]
      if @user.update user_params
        flash[:success] = "Successed"
        redirect_to admin_users_path
      else
        flash[:alert] = "Something was wrong"
        @class_users = ClassUser.asc_name
        render :edit
      end
    end

    def create
      @user = User.new(user_params)

      if @user.save
        @user_access = UserAccess.new(user_id: @user.id);
        if(@user_access.save)
          flash[:success] = "Successed"
          redirect_to admin_users_path
        else
          flash[:danger] = "can't add user access"
          @class_users = ClassUser.asc_name
          render :new
        end
      else
          flash[:danger] = "No No No No No No No"
          @class_users = ClassUser.asc_name
          render :new
      end
    end

    def destroy
      @user = User.find_by id: params[:id]
      if @user.destroy
        flash[:success] = "success"
      else
        flash[:danger] = "danger"
      end
      redirect_to admin_users_path
    end

    def user_params
      params.require(:user).permit(:id, :Tk, :password, :name, :birthday, :email, :role, :class_user_id)
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :find_user, only: %i(edit update)
  def show
    @user = User.find(params[:id])
  end

  def edit; end

  def update
      if (@user.update(update_params))
        flash[:success] = "thay đổi thành công"
        redirect_to edit_user_path(@user)
      else
        flash[:alert] = "Không thành công"
        redirect_to edit_user_path(@user)
      end
  end

  private

  def update_params
    params.required(:user).permit(:id, :password, :password_confirmation, :name, :birthday, :email)
  end

  def find_user
    @user = User.find_by id: params[:id]
    return if @user

    flash[:danger] = "Not found user"
    redirect_to root_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="admin-page">
  <div> <%= render "admin/static_pages/sidebar" %> </div>
  <div class="form-container">
    <div class="form row">
      <div class="edit-account">
        <p class="form-title">Cập nhật tài khoản</p>
        <%= form_for [:admin, @user] do |f| %>
          <%= render "admin/shared/error_messages", object: f.object %>
          <%= f.label :username, "Tài khoản" %>
          <%= f.text_field :Tk, class: "form-control"%>
          <%= f.label :password, "Mật khẩu" %>
          <%= f.password_field :password, class: "form-control" %>
          <%= f.label :name, "Tên" %>
          <%= f.text_field :name, class: "form-control" %>
          <%= f.label :birthday, "Ngày sinh" %>
          <%= f.date_field :birthday, class: "form-control" %>
          <%= f.label :email, "Email" %>
          <%= f.text_field :email, class: "form-control"%>
          <%= f.label :role, "Chức vụ" %>
          <%= f.select :role, options_for_select([["Admin", "admin"],["Teacher", "teacher"], ["Student", "student"]], :selected => @user.role), class: "form-control"%>
          <%= f.label :id_lop, "Lớp" %>
          <%= collection_select(:user, :class_user_id, @class_users, :id, :name) %>
          <%= f.submit "Edit", class: "submit-btn" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="admin-page">
  <div> <%= render "admin/static_pages/sidebar" %> </div>
  <div class="account-manage-page">
    <div class="container">
      <%= search_form_for [:admin, @q] do |f| %>
        <div class="form-section">
          <div class="col-9">
            <%= f.label :name_cont, "Tên" %>
            <%= f.search_field :name_cont %>
          </div>
          <div class="col-1">
            <%= f.label :role_eq, "Chức vụ" %>
            <%= f.select :role_eq, User.roles.keys, include_blank: true , class: "form-control"%>
          </div>
        </div>
        <%= f.submit %>
      <% end %>
    </div>
    <table class="rwd-table">
      <thead>
        <tr>
          <th>Tên</th>
          <th>Email</th>
          <th>Ngày sinh</th>
          <th>Lớp</th>
          <th>Chức vụ</th>
          <th>Lượt truy cập trong ngày</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.birthday %></td>
            <td><%= user.class_user_name ? user.class_user_name : "N/A" %></td>
            <td><%= user.role %></td>
            <% if !user.user_access.nil? %>
            <td><%= user.user_access.num_access %></td>
            <%else%>
              <td><%= "N/A" %></td>
            <%end%>
            <td>
              <div class="action-btn">
                <%= link_to edit_admin_user_path(user) do %>
                  <span class="fa fa-edit"></span>
                <% end %>
                <%= link_to admin_user_path(user), method: :delete, data: { confirm: "Bạn có chắc là muốn xóa không?" } do %>
                  <span class="fa fa-trash"></span>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%== pagy_nav(@pagy) %>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="admin-page">
  <div> <%= render "admin/static_pages/sidebar" %> </div>
  <div class="form-container">
    <div class="form row">
      <div class="edit-account">
        <p class="form-title">Tài khoản mới</p>
        <%= form_for [:admin, @user] do |f| %>
          <%= render "admin/shared/error_messages", object: f.object %>
          <%= f.label :username, "Tài khoản (*)" %>
          <%= f.text_field :Tk, class: "form-control"%>
          <%= f.label :password, "Mật khẩu (*)" %>
          <%= f.password_field :password, class: "form-control" %>
          <%= f.label :name, "Tên (*)" %>
          <%= f.text_field :name, class: "form-control" %>
          <%= f.label :birthday, "Ngày sinh" %>
          <%= f.date_field :birthday, class: "form-control" %>
          <%= f.label :role, "Chức vụ" %>
          <%= f.select :role, User.roles.keys, class: "form-control"%>
          <%= f.label :id_lop, "Lớp" %>
          <%= collection_select(:user, :class_user_id, @class_users, :id, :name) %>
          <%= f.submit "New", class: "submit-btn" %>
        <% end %>
      </div>
    </div>
  </div>
</div>